### ISSUE TITLE
Add Option to round path edges

### ISSUE THREAD

**Issue by JulianBissekkou** [xqwzts/flutter_circular_chart#11]
It would be really cool to round the stroke edges.
Here is an example !
<img width="279" alt="bildschirmfoto 2018-05-01 um 15 34 16" src="https://user-images.githubusercontent.com/36447137/39474627-2e5e15d6-4d55-11e8-92d1-5ce5155ff6d8.png">

**Comment by stefanschaller** [comment]
Thats a good Idea! Hope for an small update!

**Comment by stefanschaller** [comment]
I'm looking forward to see this in the next version !

**Comment by xqwzts** [comment]
Thanks for opening the issue, this should be relatively straightforward to do by adding a `StrokeCap.round` when painting the segments, and exposing an option to users to set it.

I'll try to get it done in the next few days, should have some downtime coming up, meanwhile PRs welcome [but please mention if you're picking it up!]

**Comment by saibotma** [comment]
Wow :O great stuff going on here! 
Thanks :)

**Comment by xqwzts** [comment]
This is now available in version 0.0.3 :tada: 

You can pass in an `edgeStyle` property to your chart and set it to `SegmentEdgeStyle.round` for the rounded caps.

I've added some documentation it in this section of the readme: https://github.com/xqwzts/flutter_circular_chart#segment-edge-style 

Thanks again for bringing up the feature @JulianBissekkou , I might not have the time to work on them immediately, but opening issues is really the best way to bring feature requests and bug reports to my attention.
