### ISSUE TITLE
Add a label in the hole of a radial chart

### ISSUE THREAD

**Issue by xqwzts** [xqwzts/flutter_circular_chart#6]
Calculate the positioning of the label based on the `holeRadius` and center it in the chart.

**Comment by bramvbilsen** [comment]
I'd also love to see this implemented!

**Comment by xqwzts** [comment]
I'm hoping to revisit all the open issues over the next week or so to bring it up to a publishable state :)

**Comment by xqwzts** [comment]
This is now done:

Labels can be included by passing in a `holeLabel` string, and optionally styled by passing in a `labelStyle` `TextStyle` to the `AnimatedCircularChart` constructor.

The [AnimatedRadialChartExample](https://github.com/xqwzts/flutter_circular_chart/blob/master/example/animated_radial_chart_example.dart#L102) now does this, resulting in:

![animated_radial_chart_example_label](https://user-images.githubusercontent.com/798935/37692307-66d6fc8a-2cc0-11e8-8e43-2fe25987bc1b.gif)

**Comment by arvanus** [comment]
Is it possible to show in the label some data referring the clicked value in the chart?
Explaining: when the user taps the chart data, display some kind of label inside the chart?
Thanks!
