### ISSUE TITLE
How to create GlobalKey?

### ISSUE THREAD

**Issue by zarub2k** [xqwzts/flutter_circular_chart#8]
I have no idea how to create final GlobalKey<AnimatedCircularChartState> _chartKey; It is not clearly mentioned in the document. I am new to Dart + Flutter

Without even passing this object my chart is rendered properly. What am I missing then?

**Comment by xqwzts** [comment]
Thanks for pointing that out @zarub2k , the readme is actually missing the initializer there, it should be:

```dart
final GlobalKey<AnimatedCircularChartState> _chartKey = new GlobalKey<AnimatedCircularChartState>();
```

The point of a GlobalKey in flutter is to have a reference to an object, usually the State of a StatefulWidget. The [flutter docs](https://docs.flutter.io/flutter/widgets/GlobalKey-class.html) mention:

> Global keys uniquely identify elements. Global keys provide access to other objects that are associated with elements, such as the a BuildContext and, for StatefulWidgets, a State.

It's a common pattern for animated widgets to have methods on their State which allow users to drive their animation, to be able to call that method you need to have a reference to the State, which is where the GlobalKey comes in.

Specifically for `AnimatedCircularChart`, when we want to update the data and drive an animation, we need to call [AnimatedCircularChartState.updateData()](https://github.com/xqwzts/flutter_circular_chart/blob/master/lib/src/animated_circular_chart.dart#L173). So we'll use a GlobalKey to always have a reference to our chart, and we can call `updateData` via that key:

```dart
chartKey.currentState.updateData(newData);
```

Note that the key is not required, so not using one will not break your widget. You just won't be able to update the data and animate the changes.

**Comment by xqwzts** [comment]
I've updated the readme, you can also take a look at the different [examples](https://github.com/xqwzts/flutter_circular_chart/tree/master/example) for actual working apps.

**Comment by zarub2k** [comment]
Thanks for the hint. You can close the issue
